#!/usr/bin/env bash
usage() {
	echo "$0 <classname> <options>"
}

CURR_PWD=${PWD}
cd $(dirname $0)
SCRIPT_PWD=${PWD}
cd $CURR_PWD

TARGET=${SCRIPT_PWD}/mallet-core/target

if [ ! -d $TARGET ]
then
	(cd $SCRIPT_PWD && ./compile)
fi

DEPENDENCIES=${TARGET}/dependency

if [ ! -d $DEPENDENCIES ]
then
	(cd $SCRIPT_PWD && mvn dependency:copy-dependencies)
fi

if [[ ""$@"" == """" ]]
then
	usage
	exit 1
fi

java -cp ${TARGET}/classes:$(echo $(ls ${DEPENDENCIES}/*.jar) | sed -e 's/ /:/g' ) $@


